### ISSUE TITLE
Internal Server Error with Export on Contao 4.12.x

### ISSUE THREAD

**Issue by hwit-biz** [BugBuster1701/contao-dlstats-statistic-export-bundle#14]
Hi there,

probably due to changed Symfony behaviour of current version 5 with the definition of services there actually appears an error while exporting dlstats via the contao-dlstats-statistic-export-bundle:

> Internal Server Error
> Was ist das Problem?
> "BugBuster\DlstatsExportBundle\Controller\ExportController" has no container set, did you forget to define it as a service subscriber?

I could fix the error by inserting some code for the ExportController service to the corresponding file [services47.yml](https://github.com/BugBuster1701/contao-dlstats-statistic-export-bundle/blob/master/src/Resources/config/services47.yml) as following:

```
services:
    bugbuster.dlstatsexport.form.type.request_token:
        class: BugBuster\DlstatsExportBundle\Form\Type\RequestTokenType
        arguments:
          ['@security.csrf.token_manager', '%contao.csrf_token_name%']
        tags:
            - form.type
			
    BugBuster\DlstatsExportBundle\Controller\ExportController:
        class: BugBuster\DlstatsExportBundle\Controller\ExportController
        autowire: true
        public: true
        arguments:
            - "@service_container"
```

Hope this helps you, Harry.

Edit: Fixed typo and link to services.47.yml
